### ISSUE TITLE
`git commit --allow-empty -m '[Project] Glitter'`

### ISSUE THREAD

**Issue by SoniEx2** [panicbit/glitter#10]
please run `git commit --allow-empty -m '[Project] Glitter'` on this dead project and then push it.

the project is dead anyway, this *can't* kill it further than "dead".

**Comment by panicbit** [comment]
Why?

**Comment by panicbit** [comment]
I should probably add a statement in the readme.

**Comment by SoniEx2** [comment]
the project is dead, the commit serves to mark it as abandonware.

**Comment by SoniEx2** [comment]
(the commit doesn't actually have to be empty. `--allow-empty` doesn't *force* it to be empty, anyway.)

**Comment by panicbit** [comment]
That doesn't seem to be obvious.

**Comment by SoniEx2** [comment]
just do it, it's basically trivial

**Comment by SoniEx2** [comment]
what do you have to lose on a dead project?
